server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always